version: '3.8'

services:
  proxy:
    image: nginx:latest
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    ports:
      - 443:80
    networks:
      - frontend

  root:
    build: ./root
    ports:
      - 8000
    depends_on:
      - db
    networks:
      - frontend
      - backend
    
  login:
    build: ./login
    ports:
      - 8001

  db:
    build: ./db
    depends_on:
      - psql
    ports:
      - 8080
    networks:
      - backend
      - dbs

  psql:
    image: postgres
    restart: always
    shm_size: 128mb
    networks:
      - dbs
    ports:
      - 5432
    volumes:
      - PGSTORAGE:/var/lib/postgresql/storage
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rustDB
      PGDATA: /var/lib/postgresql/data

  cache:
    image: redis
    networks:
      - dbs
    ports:
      - 6379

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
  dbs:
    driver: bridge

volumes:
  PGSTORAGE: {}
